name: Action Server
on:
  push:
    branches:
    - '*'
    - '!master' 
    
    
jobs:
  action_server_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github action
        uses: actions/checkout@v2
      - name: checkout Rasa github action
        uses: RasaHQ/rasa-action-server-gha@v1.0.3
        with:
          actions_directory: ./actions
          requirements_file: ./actions/requirements.txt
          docker_registry: docker.io
          docker_registry_login: ${{secrets.DOCKER_HUB_LOGIN}}
          docker_registry_password: ${{secrets.DOCKER_HUB_PASSWORD}}
          docker_image_name: ${{secrets.DOCKER_HUB_LOGIN}}/image_name
          docker_image_tag: 1
          docker_registry_push: true
          rasa_sdk_version: 2.2.0
